import { useEffect, useState } from "react";
import { ArrowUpRight, ChevronDown, Clock3, Crosshair, FileSearch, Leaf, LockKeyhole, Mail, Menu, Search, ShieldCheck, Smartphone, Sparkles, X } from "lucide-react";

const CHECKOUT = "https://pay.hotmart.com/O107466069Q?checkoutMode=10&bid=1788507646008";
const HERO = "/assets/nature-hero.jpg";
const HERBS = "/assets/nature-carousel-herbs.jpg";
const APP_SCENE = "/assets/nature-preparation.jpg";
const ORGANS = "/assets/nature-organs.jpg";

const chapters = [
  ["🚨", "Notfalldossier", "Erste Hilfe im Gelände bei plötzlichen Schmerzen, Verbrennungen, Schnittwunden und zur sofortigen Unterstützung mit natürlichen Mitteln."],
  ["🌿", "Filtros Biológicos", "Leber, rins e vesícula: combinações tradicionais para o cuidado e a purificação profunda."],
  ["🩸", "Kreislaufoptimierung", "Traditionelle Kombinationen für Herz, Kreislauf und vaskuläres Wohlbefinden."],
  ["🛑", "Schmerzlinderung", "Warme Kompressen, Salben und Pflanzenöle zur Unterstützung bei Schmerzen und Entzündungen."],
  ["🧠", "Schutz von Nerven und Immunsystem", "Traditionelle Wirkstoffe zur Unterstützung von Schlaf, geistiger Klarheit und natürlicher Widerstandskraft."],
] as const;

const faqs = [
  ["Wie funktioniert der Erste-Hilfe-Leitfaden in der Praxis?", "Er funktioniert wie ein Notfallknopf in der Benutzeroberfläche der Anwendung. Öffnen Sie den Reiter „Erste Hilfe“, wählen Sie den Vorfall und finden Sie sofort die empfohlenen Maßnahmen und natürlichen Ressourcen für die ersten Minuten."],
  ["Wie werden die Zugangsdaten bereitgestellt?", "Der Prozess wird vollständig von Hotmart automatisiert. Sobald die Zahlung von 33 € verarbeitet ist, erhalten Sie den verschlüsselten Link per Kauf-E-Mail, um Ihr Passwort zu registrieren und sofort auf die Web-App zuzugreifen."],
  ["Das System substitui orientação médica?", "Nein. Das Ökosystem vermittelt traditionelles Wissen für Unterstützung, Prävention, Linderung und Erste Hilfe im Gelände. Es ist ergänzend und ersetzt weder Untersuchungen, Diagnosen noch professionelle Eingriffe."],
];

function Cta({ children, outline = false }: { children: React.ReactNode; outline?: boolean }) { return <a className={`cta ${outline ? "cta--outline" : ""}`} href={CHECKOUT} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={16} /></a>; }
function Label({ children }: { children: React.ReactNode }) { return <div className="eyebrow"><span className="eyebrow-line" />{children}</div>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [faqOpen, setFaqOpen] = useState(0);
  const [query, setQuery] = useState("");
  const [active, setActive] = useState(0);
  useEffect(() => { document.documentElement.lang = "de-DE"; }, []);
  return <div className="dossier-shell">
    <header className="dossier-header"><a href="#top" className="dossier-brand"><span className="brand-symbol"><Leaf size={16} /></span><span>MEDICINA <strong>DA NATUREZA</strong></span></a><nav className={menuOpen ? "nav-open" : ""}><a href="#arquivo" onClick={() => setMenuOpen(false)}>Das Archiv</a><a href="#sistema" onClick={() => setMenuOpen(false)}>Das System</a><a href="#modulos" onClick={() => setMenuOpen(false)}>Module</a><a href="#acesso" onClick={() => setMenuOpen(false)}>Zugang</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a></nav><div className="header-right"><span className="header-status"><i /> System online</span><Cta>Zugang aktivieren</Cta><button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menü öffnen">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    <main id="top">
      <section className="dossier-hero"><div className="hero-backdrop" style={{ backgroundImage: `linear-gradient(90deg, rgba(5,15,11,.98) 0%, rgba(5,15,11,.89) 42%, rgba(5,15,11,.38) 100%), url(${HERO})` }} /><div className="hero-gridline" /><div className="hero-content"><div className="file-tag"><LockKeyhole size={13} /> REGISTRIERT: VERTRAULICH · ARCHIV DER AHNEN</div><h1>Das Archiv apagado<br /><em>der Naturheilkunde.</em></h1><p className="hero-lead">Das Wissen, das vergangene Generationen zum Schutz des Körpers nutzten, wurde wiederentdeckt und in einen <strong>digitalen Mechanismus zur biologischen Rückgewinnung integriert.</strong></p><p className="hero-support">Mehr als 300 Lösungen, Wirkstoffkombinationen und natürliche Ressourcen – sofort in Ihrem Browser verfügbar.</p><div className="hero-actions"><Cta>ZUGANG ZUM SYSTEM ENTSCHLÜSSELN</Cta><a href="#arquivo" className="scroll-link">DOSSIER ERKUNDEN <span>↓</span></a></div><div className="hero-meta"><span><ShieldCheck size={14} /> Zugang criptografado</span><span><Smartphone size={14} /> Web-App-PWA-Technologie</span><span><Clock3 size={14} /> Lebenslanger Zugang</span></div></div><div className="hero-stamp"><span>MEDICINA<br />DA NATUREZA</span><strong>300+</strong><small>WIEDERGEFUNDENE LÖSUNGEN</small></div></section>

      <section id="arquivo" className="archive-section"><div className="section-number">01</div><div className="archive-copy"><Label>DAS GELÖSCHTE ARCHIV</Label><h2>Was wussten vergangene Generationen, das vor Ihnen verborgen wurde?</h2><p>In der Geschichte der Menschheit existiert eine verborgene Zeitlinie. Jahrtausendelang schützten Ahnengenerationen den Körper mit bioaktiven Komplexen, die direkt aus der Erde gewonnen wurden.</p><p>Heute wurde dieses Wissen wiedergewonnen und in einen digitalen Mechanismus zur biologischen Rückgewinnung integriert – eine praktische Karte natürlicher Ressourcen, verantwortungsvoll recherchierbar und anwendbar.</p><Cta outline>ICH MÖCHTE MEINEN LEBENSLANGEN ZUGANG AKTIVIEREN</Cta></div><div className="document-visual"><div className="document-card"><div className="document-top"><span>ARCHIV 001 / BOTANIK</span><span>VERTRAULICH</span></div><img src={HERBS} alt="Dokumentierte Kräuter und Wurzeln" /><div className="document-caption"><FileSearch size={15} /> REGISTRIERUNG ANCESTRALER RESSOURCEN</div></div><div className="timeline"><span>TRADITION</span><i /><span>RÜCKGEWINNUNG</span><i /><span>SYSTEM</span></div></div></section>

      <section className="chapter-section chapter-dark"><div className="chapter-heading"><Label>KAPITEL I</Label><h2>DIE INDUSTRIE DES DAUERHAFTEN SYMPTOMS</h2><p>Die Diagnose des Feindes, den niemand zu enthüllen wagt.</p></div><div className="chapter-text"><h3>DIE MILLIARDENSCHWERE MASCHINERIE WILL NICHT IHRE HEILUNG. SIE BRAUCHT IHRE MONATLICHE UNTERSCHRIFT.</h3><p>Analysieren Sie die aktuelle Lage wie ein Ermittler: Wenn synthetische Wirkstoffe Ihr Problem lösen sollten, warum müssen Sie dieselbe Packung Monat für Monat weiter kaufen?</p><p>Ihre Vorfahren kannten die Eigenschaften und Potenzen jeder Pflanze, Rinde und Wurzel. Wir gewinnen diese natürliche Autorität zurück und beseitigen die einzige Barriere: die Schwierigkeit, sie zu finden und zuzubereiten.</p><div className="quote-line">„Vergessen Sie riesige Dateien und verstreute Informationen. Finden Sie die passende Kombination von Ressourcen in Sekunden über eine intelligente Suchleiste.“</div></div></section>

      <section id="sistema" className="system-section"><div className="system-intro"><Label>KAPITEL II · O SYSTEM</Label><h2>DIE TECHNOLOGIE DER AHNEN-RÜCKGEWINNUNG</h2><p>Mehr als 300 traditionelle Protokolle und biologische Überlebensleitfäden in einer interaktiven digitalen Umgebung.</p><div className="system-points"><div><span>01</span><strong>SUCHEN</strong><small>Geben Sie Symptom, Schmerz oder betroffenes Organ ein.</small></div><div><span>02</span><strong>KOMBINIEREN</strong><small>Das System cruza os dados e organiza os recursos.</small></div><div><span>03</span><strong>ANWENDEN</strong><small>Erhalten Sie die Schritt-für-Schritt-Anleitung im richtigen Moment.</small></div></div></div><div className="app-mockup"><div className="app-bar"><span className="app-logo"><Leaf size={14} /></span><span>NATURHEILKUNDE</span><span className="app-live">● LIVE</span></div><div className="app-body"><div className="app-kicker">SUCHMECHANISMUS</div><h3>Was möchten Sie untersuchen?</h3><div className="search-box"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Symptom, Schmerz oder Organ eingeben..." /><kbd>⌘ K</kbd></div><div className="app-result"><div className="result-icon"><Crosshair size={18} /></div><div><span>PROTOKOLL GEFUNDEN</span><strong>{query || "Erste Hilfe im Gelände"}</strong><small>Geordnete Ressourcen · Schritt-für-Schritt-Anwendung</small></div><ArrowUpRight size={16} /></div><div className="app-tags"><span>Leber</span><span>Kreislauf</span><span>Entzündung</span><span>Notfall</span></div></div></div></section>

      <section className="feature-strip"><div className="feature-image" style={{ backgroundImage: `url(${APP_SCENE})` }} /><div className="feature-content"><Label>DER MECHANISMUS</Label><h2>Ein natürliches Verteidigungswerkzeug in Ihrer Hand.</h2><div className="feature-list"><article><span>↗</span><div><h3>LEITFADEN FÜR ERSTE HILFE IM GELÄNDE</h3><p>Ein Schnellreaktionsprotokoll für häusliche Unfälle, akute Krisen und unerwartete Situationen.</p></div></article><article><span>⇄</span><div><h3>INTELLIGENZ FÜR GLEICHWERTIGEN ERSATZ</h3><p>Wenn ein Inhaltsstoff in Ihrer Region nicht verfügbar ist, finden Sie Alternativen mit ähnlichen Eigenschaften.</p></div></article><article><span>◌</span><div><h3>FORTGESCHRITTENE AKTIVE EXTRAKTION</h3><p>Zeit, Mengenverhältnisse und Gefäße werden erklärt, damit die Methode praktisch wird.</p></div></article></div><Cta>DAS NATURHEILKUNDE-ARSENAL ENTFESSELN</Cta></div></section>

      <section id="modulos" className="modules-section"><div className="modules-head"><div><Label>KAPITEL III · DIE KARTE</Label><h2>DIE UNABHÄNGIGE LEBENSAPOTHEKE</h2></div><p>Das System unterteilt jahrhundertealtes Erfahrungswissen in strukturierte und präzise Module.</p></div><div className="module-grid">{chapters.map(([icon, title, text], i) => <button className={`module-card ${active === i ? "active" : ""}`} key={title} onClick={() => setActive(i)}><span className="module-index">0{i + 1}</span><span className="module-icon">{icon}</span><h3>{title}</h3><p>{text}</p><span className="module-arrow">↗</span></button>)}</div><div className="module-foot"><span>WÄHLEN SIE EIN MODUL FÜR DEN DOSSIER-ZUGANG</span><span>{String(active + 1).padStart(2, "0")} / 05</span></div></section>

      <section className="transformation chapter-dark"><div><Label>KAPITEL IV · DIE SOFORTIGE VERWANDLUNG</Label><h2>WARUM SIE DIESES SYSTEM NOCH HEUTE BRAUCHEN</h2></div><p>Dieses Produkt macht Sie zum Beschützer Ihres Zuhauses. Sie sind nicht länger von Apotheken abhängig, sondern wissen genau, wo Sie Informationen finden, wenn jemand Hilfe braucht. Das Wissen von Generationen – übersetzt in strukturierte, übersichtliche und praktische Listen für Ihren Alltag.</p></section>

      <section id="acesso" className="offer-section"><div className="offer-card"><div className="offer-seal"><ShieldCheck size={23} /><span>15 TAGE<br /><b>RISIKOFREI</b></span></div><Label>KAPITEL V · DER WERT IHRER FREIHEIT</Label><h2>AKTIVIEREN SIE DEN ZUGANG ZUM VOLLSTÄNDIGEN ARCHIV.</h2><p>Der Zugang kostet weniger als eine Packung Markenmedikamente in Ihrer Apotheke.</p><div className="price-line"><span>Lebenslanger Zugang</span><strong>33€</strong><span>einmalige Zahlung über Hotmart</span></div><Cta>ICH MÖCHTE MEINEN LEBENSLANGEN ZUGANG FÜR 33 €</Cta><small>Keine Monatsgebühren · Keine automatischen Verlängerungen · Verschlüsselter Zugang</small></div></section>

      <section id="faq" className="faq-section"><div className="faq-heading"><Label>HÄUFIG GESTELLTE FRAGEN</Label><h2>DOSSIER-FAQ</h2><p>Klare Informationen, bevor Sie Ihren Zugang freischalten.</p></div><div className="faq-list">{faqs.map(([q, a], i) => <div className={`faq-item ${faqOpen === i ? "open" : ""}`} key={q}><button onClick={() => setFaqOpen(faqOpen === i ? -1 : i)}><span>{q}</span><ChevronDown size={18} /></button><div className="faq-answer"><p>{a}</p></div></div>)}</div></section>
      <section className="closing-section"><span className="closing-mark">✦</span><h2>Sie haben jetzt die Wahl: Entweder Sie unterstützen weiterhin das System, das von Ihren Symptomen profitiert, oder Sie übernehmen die Kontrolle über Ihre Gesundheit.</h2><Cta>SYSTEMZUGRIFF ENTSCHLÜSSELN</Cta></section>
    </main>
    <footer className="dossier-footer"><div className="footer-brand"><span className="brand-symbol"><Leaf size={14} /></span><span>NATURHEILKUNDE</span></div><p>Diese digitale Umgebung enthält historische und informative Dokumentationen zu Pflanzenkombinationen, traditionellen biologischen Ressourcen und überlieferten Erste-Hilfe-Praktiken. Die Informationen stellen keine individuelle medizinische Beratung, Diagnose oder Behandlung dar. Lassen Sie sich regelmäßig von qualifizierten Fachkräften untersuchen und wenden Sie sich stets an Experten für natürliche Ressourcen.</p><a href="mailto:contact@medizin-der-natur.de"><Mail size={14} /> contact@medizin-der-natur.de</a></footer>
  </div>;
}
