import { useEffect, useState } from "react";
import { ArrowUpRight, ChevronDown, Clock3, Crosshair, FileSearch, Leaf, LockKeyhole, Mail, Menu, Search, ShieldCheck, Smartphone, Sparkles, X } from "lucide-react";

const CHECKOUT = "https://pay.hotmart.com/O107466069Q?checkoutMode=10&bid=1788507646008";
const HERO = "/assets/nature-hero.jpg";
const HERBS = "/assets/nature-carousel-herbs.jpg";
const APP_SCENE = "/assets/nature-preparation.jpg";
const ORGANS = "/assets/nature-organs.jpg";

const chapters = [
  ["🚨", "Dossiê Emergencial", "Primeiros socorros de campo para dores súbitas, queimaduras, cortes e suporte imediato com recursos naturais."],
  ["🌿", "Filtros Biológicos", "Fígado, rins e vesícula: combinações tradicionais para o cuidado e a purificação profunda."],
  ["🩸", "Engenharia Circulatória", "Recursos naturais organizados para coração, circulação e bem-estar vascular."],
  ["🛑", "Bloqueio de Dor", "Compressas mornas, unguentos e óleos botânicos para o cuidado de dores e inflamações."],
  ["🧠", "Blindagem Neural", "Ativos tradicionais para apoiar sono, clareza mental e resistência natural."],
] as const;

const faqs = [
  ["Como o Guia de Primeiros Socorros funciona na prática?", "Ele funciona como um botão de pânico na interface do aplicativo. Você acessa a aba de Primeiros Socorros, seleciona o tipo de ocorrência e encontra as ações e recursos indicados para os primeiros minutos."],
  ["Como funciona a entrega das credenciais?", "O processo é automatizado pela Hotmart. Assim que o pagamento de 33€ é processado, o link criptografado chega no e-mail de compra para cadastro da senha e acesso ao Web App."],
  ["O sistema substitui orientação médica?", "Não. O ecossistema reúne conhecimento tradicional para suporte, prevenção, alívio e primeiros socorros de campo. Ele é complementar e não substitui exames, diagnóstico ou intervenções profissionais."],
];

function Cta({ children, outline = false }: { children: React.ReactNode; outline?: boolean }) { return <a className={`cta ${outline ? "cta--outline" : ""}`} href={CHECKOUT} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={16} /></a>; }
function Label({ children }: { children: React.ReactNode }) { return <div className="eyebrow"><span className="eyebrow-line" />{children}</div>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [faqOpen, setFaqOpen] = useState(0);
  const [query, setQuery] = useState("");
  const [active, setActive] = useState(0);
  useEffect(() => { document.documentElement.lang = "pt-BR"; }, []);
  return <div className="dossier-shell">
    <header className="dossier-header"><a href="#top" className="dossier-brand"><span className="brand-symbol"><Leaf size={16} /></span><span>MEDICINA <strong>DA NATUREZA</strong></span></a><nav className={menuOpen ? "nav-open" : ""}><a href="#arquivo" onClick={() => setMenuOpen(false)}>O arquivo</a><a href="#sistema" onClick={() => setMenuOpen(false)}>O sistema</a><a href="#modulos" onClick={() => setMenuOpen(false)}>Módulos</a><a href="#acesso" onClick={() => setMenuOpen(false)}>Acesso</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a></nav><div className="header-right"><span className="header-status"><i /> Sistema online</span><Cta>Ativar acesso</Cta><button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    <main id="top">
      <section className="dossier-hero"><div className="hero-backdrop" style={{ backgroundImage: `linear-gradient(90deg, rgba(5,15,11,.98) 0%, rgba(5,15,11,.89) 42%, rgba(5,15,11,.38) 100%), url(${HERO})` }} /><div className="hero-gridline" /><div className="hero-content"><div className="file-tag"><LockKeyhole size={13} /> REGISTRO: CONFIDENCIAL · ARQUIVO ANCESTRAL</div><h1>O arquivo apagado<br /><em>da medicina natural.</em></h1><p className="hero-lead">O conhecimento que as gerações passadas usavam para proteger o corpo foi recuperado e integrado em um <strong>Mecanismo Digital de Resgate Biológico.</strong></p><p className="hero-support">Mais de 300 soluções, combinações de ativos e recursos naturais organizados para acesso imediato no seu navegador.</p><div className="hero-actions"><Cta>Descriptografar acesso ao sistema</Cta><a href="#arquivo" className="scroll-link">Explorar o dossiê <span>↓</span></a></div><div className="hero-meta"><span><ShieldCheck size={14} /> Acesso criptografado</span><span><Smartphone size={14} /> Tecnologia Web App PWA</span><span><Clock3 size={14} /> Acesso vitalício</span></div></div><div className="hero-stamp"><span>MEDICINA<br />DA NATUREZA</span><strong>300+</strong><small>SOLUÇÕES RECUPERADAS</small></div></section>

      <section id="arquivo" className="archive-section"><div className="section-number">01</div><div className="archive-copy"><Label>O ARQUIVO APAGADO</Label><h2>O que as gerações passadas sabiam que foi escondido de você?</h2><p>Há uma linha do tempo oculta na história da humanidade. Por milhares de anos, linhagens ancestrais mantiveram o corpo protegido usando complexos bioativos extraídos da própria Terra.</p><p>Hoje, esse conhecimento foi recuperado e integrado em um mecanismo digital de resgate biológico. Um mapa prático de recursos naturais para pesquisar, compreender e aplicar com responsabilidade.</p><Cta outline>Quero ativar meu acesso vitalício</Cta></div><div className="document-visual"><div className="document-card"><div className="document-top"><span>ARQUIVO 001 / BOTÂNICA</span><span>CONFIDENCIAL</span></div><img src={HERBS} alt="Ervas e raízes naturais documentadas" /><div className="document-caption"><FileSearch size={15} /> Registro de recursos ancestrais</div></div><div className="timeline"><span>TRADIÇÃO</span><i /><span>RESGATE</span><i /><span>SISTEMA</span></div></div></section>

      <section className="chapter-section chapter-dark"><div className="chapter-heading"><Label>CAPÍTULO I</Label><h2>A indústria do sintoma perpétuo</h2><p>O diagnóstico do vilão que ninguém ousa revelar.</p></div><div className="chapter-text"><h3>A engrenagem bilionária não quer a sua cura. Ela precisa da sua assinatura mensal.</h3><p>Analise o cenário atual como um investigador: se os compostos sintéticos fossem feitos para solucionar seu problema, por que você precisa continuar comprando a mesma caixa mês após mês?</p><p>Seus ancestrais conheciam as substâncias e potências de cada folha, casca e raiz. Nós resgatamos essa autoridade natural e removemos a única barreira que existia: a dificuldade de encontrar e preparar.</p><div className="quote-line">“Esqueça arquivos gigantes e informações dispersas. Encontre a combinação de recursos em segundos através de uma barra de busca inteligente.”</div></div></section>

      <section id="sistema" className="system-section"><div className="system-intro"><Label>CAPÍTULO II · O SISTEMA</Label><h2>A tecnologia de resgate ancestral</h2><p>Mais de 300 protocolos tradicionais e guias de sobrevivência biológica dentro de um ambiente digital interativo.</p><div className="system-points"><div><span>01</span><strong>Pesquise</strong><small>Digite o sintoma, a dor ou o órgão afetado.</small></div><div><span>02</span><strong>Combine</strong><small>O sistema cruza os dados e organiza os recursos.</small></div><div><span>03</span><strong>Aplique</strong><small>Receba o passo a passo no momento necessário.</small></div></div></div><div className="app-mockup"><div className="app-bar"><span className="app-logo"><Leaf size={14} /></span><span>MEDICINA DA NATUREZA</span><span className="app-live">● AO VIVO</span></div><div className="app-body"><div className="app-kicker">MECANISMO DE BUSCA</div><h3>O que você precisa investigar?</h3><div className="search-box"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Digite sintoma, dor ou órgão..." /><kbd>⌘ K</kbd></div><div className="app-result"><div className="result-icon"><Crosshair size={18} /></div><div><span>PROTOCOLO ENCONTRADO</span><strong>{query || "Primeiros socorros de campo"}</strong><small>Recursos organizados · Aplicação passo a passo</small></div><ArrowUpRight size={16} /></div><div className="app-tags"><span>Fígado</span><span>Circulação</span><span>Inflamação</span><span>Emergência</span></div></div></div></section>

      <section className="feature-strip"><div className="feature-image" style={{ backgroundImage: `url(${APP_SCENE})` }} /><div className="feature-content"><Label>O MECANISMO</Label><h2>Uma ferramenta de defesa natural na palma da sua mão.</h2><div className="feature-list"><article><span>↗</span><div><h3>Guia de Primeiros Socorros de Campo</h3><p>Um protocolo de resposta rápida para acidentes domésticos, crises agudas e situações inesperadas.</p></div></article><article><span>⇄</span><div><h3>Inteligência de Substituição Equivalente</h3><p>Se um ingrediente não existe na sua região, encontre alternativas com propriedades semelhantes.</p></div></article><article><span>◌</span><div><h3>Extração Ativa Avançada</h3><p>Tempo, proporções e recipientes explicados para transformar o método em prática.</p></div></article></div><Cta> liberar o arsenal natural</Cta></div></section>

      <section id="modulos" className="modules-section"><div className="modules-head"><div><Label>CAPÍTULO III · O MAPA</Label><h2>A farmácia viva independente</h2></div><p>O sistema divide séculos de conhecimento empírico em módulos estruturados e objetivos.</p></div><div className="module-grid">{chapters.map(([icon, title, text], i) => <button className={`module-card ${active === i ? "active" : ""}`} key={title} onClick={() => setActive(i)}><span className="module-index">0{i + 1}</span><span className="module-icon">{icon}</span><h3>{title}</h3><p>{text}</p><span className="module-arrow">↗</span></button>)}</div><div className="module-foot"><span>SELECIONE UM MÓDULO PARA ACESSAR O DOSSIÊ</span><span>{String(active + 1).padStart(2, "0")} / 05</span></div></section>

      <section className="transformation chapter-dark"><div><Label>CAPÍTULO IV · A TRANSFORMAÇÃO</Label><h2>O motivo pelo qual você precisa desse sistema hoje.</h2></div><p>Este produto transforma você no protetor da sua casa. Você deixa de ser uma vítima dependente das farmácias e passa a ser a pessoa que sabe exatamente onde buscar informação quando alguém precisa de ajuda. É o conhecimento de gerações traduzido em listas estruturadas, limpas e práticas para o seu dia a dia.</p></section>

      <section id="acesso" className="offer-section"><div className="offer-card"><div className="offer-seal"><ShieldCheck size={23} /><span>15 DIAS<br /><b>SEM RISCO</b></span></div><Label>CAPÍTULO V · O VALOR DA LIBERTAÇÃO</Label><h2>Ative o acesso ao arquivo completo.</h2><p>Adquirir o acesso custa menos do que uma única caixa de medicamentos de marca.</p><div className="price-line"><span>Acesso vitalício</span><strong>33€</strong><span>pagamento único via Hotmart</span></div><Cta>Quero meu acesso vitalício por 33€</Cta><small>Sem taxas mensais · Sem renovações automáticas · Acesso criptografado</small></div></section>

      <section id="faq" className="faq-section"><div className="faq-heading"><Label>PERGUNTAS FREQUENTES</Label><h2>FAQ do dossiê</h2><p>Informações claras antes de liberar seu acesso.</p></div><div className="faq-list">{faqs.map(([q, a], i) => <div className={`faq-item ${faqOpen === i ? "open" : ""}`} key={q}><button onClick={() => setFaqOpen(faqOpen === i ? -1 : i)}><span>{q}</span><ChevronDown size={18} /></button><div className="faq-answer"><p>{a}</p></div></div>)}</div></section>
      <section className="closing-section"><span className="closing-mark">✦</span><h2>A escolha entre continuar alimentando o sistema que lucra com os seus sintomas ou resgatar sua soberania de saúde está diante de você agora.</h2><Cta>Descriptografar meu acesso ao sistema</Cta></section>
    </main>
    <footer className="dossier-footer"><div className="footer-brand"><span className="brand-symbol"><Leaf size={14} /></span><span>MEDICINA DA NATUREZA</span></div><p>Este ambiente contém documentação histórica e informativa sobre recursos biológicos tradicionais. Não constitui aconselhamento médico personalizado, diagnóstico ou tratamento isolado. Mantenha o acompanhamento com profissionais de saúde habilitados.</p><a href="mailto:contact@medizin-der-natur.de"><Mail size={14} /> contact@medizin-der-natur.de</a></footer>
  </div>;
}
